-- total revenue generated by each hotel in the month of May
WITH revenue_cte AS (
  SELECT property_id, SUM(revenue_realized) AS total_revenue
  FROM fact_bookings
  WHERE booking_status IN ('Checked Out') AND EXTRACT(MONTH FROM check_in_date) = 5
  GROUP BY property_id
)
SELECT distinct(dh.property_name), revenue_cte.total_revenue
FROM revenue_cte
INNER JOIN dim_hotels dh ON revenue_cte.property_id = dh.property_id;

-- number of successful bookings made for each room type in each hotel on weekends
WITH weekend_bookings_cte AS (
  SELECT property_id, room_category, SUM(successful_bookings) AS total_weekend_bookings
  FROM fact_aggregated_bookings fab
  INNER JOIN dim_date dd ON fab.check_in_date = dd.date
  WHERE dd.day_type = 'weekday'
  GROUP BY property_id, room_category
)
SELECT dh.property_name, dr.room_id, weekend_bookings_cte.total_weekend_bookings
FROM weekend_bookings_cte
INNER JOIN dim_hotels dh ON weekend_bookings_cte.property_id = dh.property_id
INNER JOIN dim_rooms dr ON weekend_bookings_cte.room_category = dr.room_id;

-- total number of guests who stayed in each room type in each hotel
WITH guests_cte AS (
  SELECT property_id, room_category, SUM(no_guests) AS total_guests
  FROM fact_bookings
  WHERE booking_status IN ('Checked Out', 'No show')
  GROUP BY property_id, room_category
)
SELECT dh.property_name, dr.room_id, guests_cte.total_guests
FROM guests_cte
INNER JOIN dim_hotels dh ON guests_cte.property_id = dh.property_id
INNER JOIN dim_rooms dr ON guests_cte.room_category = dr.room_id;


