-- Total revenue generated by each hotel
SELECT property_id, SUM(revenue_generated) AS total_revenue
FROM hospitality.fact_bookings
GROUP BY property_id;
-- Total revenue realized by each hotel
SELECT property_id, SUM(revenue_realized) AS total_realized_revenue
FROM hospitality.fact_bookings
GROUP BY property_id;
-- Total revenue generated by each hotel for each room category
SELECT property_id, room_category, SUM(revenue_generated) AS total_revenue
FROM hospitality.fact_bookings
GROUP BY property_id, room_category;
-- Total revenue realized by each hotel for each room category
SELECT property_id, room_category, SUM(revenue_realized) AS total_realized_revenue
FROM hospitality.fact_bookings
GROUP BY property_id, room_category;

